export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const ORG_REGISTER_SUCCESS = "ORG_REGISTER_SUCCESS";
export const ORG_REGISTER_FAIL = "ORG_REGISTER_FAIL";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const ORG_LOGIN_SUCCESS = "ORG_LOGIN_SUCCESS";
export const ORG_LOGIN_FAIL = "ORG_LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const ORG_LOADED = "ORG_LOADED";

export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
